name: Suma Automatizada

on: [push]

jobs:
  suma-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Sumar números
      run: |
        # Definir números a sumar
        num1=5
        num2=7

        # Realizar la suma
        suma=$((num1 + num2))

        # Imprimir el resultado
        echo "La suma de $num1 y $num2 es $suma"
